Repository pluralsight/pando, pull requests merged in 2022-11, with the labels that each got.

#710 feat(shared): promote pagination flag to next
  packages/headless-styles/index.experimental.js
  packages/headless-styles/index.stable.js
  packages/shared/src/featureFlags.ts
  packages/shared/tests/flags/experimental.test.ts
  packages/shared/tests/flags/stable.test.ts
Labels: enhancement

#712 docs(headless-styles): add optgroup example to Select docs
  website/docs/development/headless-styles/Select.mdx
Labels: documentation

#718 docs: remove prefix from Select code examples
  website/src/components/Select/Select.preview.js
Labels: documentation

#720 docs: added select page
  website/docs/design/select.md
Labels: documentation

#722 docs: added avatar page
  website/docs/design/avatar.md
Labels: documentation

#725 Update intro.mdx
  website/versioned_docs/version-0.1.0-alpha/development/headless-styles/intro.mdx
Labels: documentation

#732 docs: added confirm dialog page
  website/docs/design/confirm-dialog.md
Labels: documentation, design

#733 Docs/717 use auto format api
  website/docs/development/react-utils/use-auto-format-date.mdx
Labels: documentation

#736 feat(tokens): update default-text & navigation-visited values
  packages/design-tokens/tokens/base/action.yaml
  packages/design-tokens/tokens/base/default.yaml
Labels: enhancement

#743 feat(tokens): add action-border-focus token
  packages/design-tokens/tokens/base/action.yaml
Labels: enhancement

#748 docs: up PS deps to latest next
  .pnp.cjs
  .yarn/cache/@pluralsight-design-tokens-npm-0.1.2-beta-0ad428-cb6e4bd68b-2da05aaf93.zip
  .yarn/cache/@pluralsight-design-tokens-npm-0.1.2-beta-d3019a-978562078d-911b9d0d4d.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-0ad428-48ad3e59b4-4906f6e4a9.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-dff08f-e0dae8691f-adbda53722.zip
  yarn.lock
Labels: documentation

#749 docs: added input page
  website/docs/design/input.md
Labels: documentation, design

#752 feat(shared): add menu hook experimental feature flags
  packages/shared/src/featureFlags.ts
  packages/shared/src/index.ts
  packages/shared/tests/flags/experimental.test.ts
Labels: enhancement

#757 feat(sandbox): add Tanstack router
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.20.1-8f9256f2ed-00567a333d.zip
  .yarn/cache/@tanstack-react-router-devtools-npm-0.0.1-beta.2-98486cdfe2-7ed3e4382b.zip
  .yarn/cache/@tanstack-react-router-npm-0.0.1-beta.5-fc7af13465-8ed487a587.zip
  .yarn/cache/@tanstack-router-core-npm-0.0.1-beta.5-62e82703d4-0b4c01affc.zip
  .yarn/cache/date-fns-npm-2.29.3-fef7e3c72c-e01cf5b62a.zip
  .yarn/cache/history-npm-5.3.0-00136b6a63-d73c35df49.zip
  .yarn/cache/regenerator-runtime-npm-0.13.10-57e3c1406b-09893f5a9e.zip
  .yarn/cache/tiny-invariant-npm-1.3.1-a8ca214e49-872dbd1ff2.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  packages/headless-styles/sandbox/package.json
  packages/headless-styles/sandbox/src/App.css
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/Sidebar.jsx
  packages/headless-styles/sandbox/src/main.jsx
  packages/headless-styles/sandbox/src/routes/admonition.jsx
  packages/headless-styles/sandbox/src/routes/avatar.jsx
  packages/headless-styles/sandbox/src/routes/badge.jsx
  packages/headless-styles/sandbox/src/routes/button.jsx
  packages/headless-styles/sandbox/src/routes/checkbox.jsx
  packages/headless-styles/sandbox/src/routes/circularProgress.jsx
  packages/headless-styles/sandbox/src/routes/confirmDialog.jsx
  packages/headless-styles/sandbox/src/routes/errorMessage.jsx
  packages/headless-styles/sandbox/src/routes/fieldMessage.jsx
  packages/headless-styles/sandbox/src/routes/formControl.jsx
  packages/headless-styles/sandbox/src/routes/formLabel.jsx
  packages/headless-styles/sandbox/src/routes/home.jsx
  packages/headless-styles/sandbox/src/routes/icon.jsx
  packages/headless-styles/sandbox/src/routes/iconButton.jsx
  packages/headless-styles/sandbox/src/routes/input.jsx
  packages/headless-styles/sandbox/src/routes/menu.jsx
  packages/headless-styles/sandbox/src/routes/modal.jsx
  packages/headless-styles/sandbox/src/routes/pagination.jsx
  packages/headless-styles/sandbox/src/routes/preloadedImg.jsx
  packages/headless-styles/sandbox/src/routes/progress.jsx
  packages/headless-styles/sandbox/src/routes/radio.jsx
  packages/headless-styles/sandbox/src/routes/routeConfig.js
  packages/headless-styles/sandbox/src/routes/select.jsx
  packages/headless-styles/sandbox/src/routes/skeleton.jsx
  packages/headless-styles/sandbox/src/routes/switch.jsx
  packages/headless-styles/sandbox/src/routes/table.jsx
  packages/headless-styles/sandbox/src/routes/tabs.jsx
  packages/headless-styles/sandbox/src/routes/tag.jsx
  packages/headless-styles/sandbox/src/routes/textLink.jsx
  packages/headless-styles/sandbox/src/routes/textarea.jsx
  packages/headless-styles/sandbox/src/routes/tooltip.jsx
  yarn.lock
Labels: enhancement

#761 docs(react-utils): add docs page for roving tab index hook
  website/docs/development/react-utils/use-roving-tabindex.mdx
Labels: documentation

#765 Docs/604 use submenu interaction
  website/docs/development/react-utils/use-submenu-interaction.mdx
Labels: documentation

#773 Docs/604 use menu interaction
  website/docs/development/react-utils/use-menu-interaction.mdx
Labels: documentation

#775 docs: update Input API and examples to match latest API
  .pnp.cjs
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-0ad428-48ad3e59b4-4906f6e4a9.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-1c0b7c-9d91685481-2b5014e8f5.zip
  website/docs/development/headless-styles/Input.mdx
  website/src/components/FormControl/ErrorFormControl.js
  website/src/css/custom.css
  website/src/theme/ReactLiveScope/index.js
  yarn.lock
Labels: documentation

#779 docs: update migration.md to match latest standards
  website/docs/development/getting-started/migration.md
Labels: documentation

#772 docs: added modal page
  website/docs/design/modal.md
Labels: documentation, design

#786 feat(hs): add GridJS API and tests
  packages/headless-styles/sandbox/src/components/Grid.jsx
  packages/headless-styles/src/components/Grid/gridJS.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/tests/grid/gridJS.test.ts
Labels: enhancement

#760 docs: added radio page
  website/docs/design/radio.md
Labels: documentation, design

#653 docs: add admonition page
  website/docs/design/admonition.md
Labels: documentation, design

#658 docs: initial commit of button page
  website/docs/design/button.md
  website/static/img/button-anatomy.png
Labels: documentation, design

#661 docs: add grammar page
  website/docs/design/grammar.md
Labels: discussion, design

#730 docs: added checkbox page
  website/docs/design/checkbox.md
Labels: documentation, design

#764 docs: added switch page
  website/docs/design/switch.md
Labels: documentation, design

#767 docs: added lists page
  website/docs/design/lists.md
Labels: documentation, design

#770 docs: added menu page
  website/docs/design/menu.md
Labels: documentation, design

#791 docs: added pagination page
  website/docs/design/components/_category_.yml
  website/docs/design/components/admonition.md
  website/docs/design/components/avatar.md
  website/docs/design/components/badge.md
  website/docs/design/components/button.md
  website/docs/design/components/checkbox.md
  website/docs/design/components/confirm-dialog.md
  website/docs/design/components/form-control.md
  website/docs/design/components/input.md
  website/docs/design/components/lists.md
  website/docs/design/components/menu.md
  website/docs/design/components/modal.md
  website/docs/design/components/pagination.md
  website/docs/design/components/radio.md
  website/docs/design/components/select.md
  website/docs/design/components/switch.md
  website/docs/design/content/_category_.yml
  website/docs/design/content/grammar.md
  website/docs/design/foundations/_category_.yml
  website/docs/design/foundations/color.mdx
  website/docs/start/get-started.md
  website/docusaurus.config.js
  website/versioned_docs/version-0.1.0-alpha/design/color.md
  website/versioned_docs/version-0.1.0-alpha/design/components/_category_.yml
  website/versioned_docs/version-0.1.0-alpha/design/components/admonition.md
  website/versioned_docs/version-0.1.0-alpha/design/components/avatar.md
  website/versioned_docs/version-0.1.0-alpha/design/components/badge.md
  website/versioned_docs/version-0.1.0-alpha/design/components/button.md
  website/versioned_docs/version-0.1.0-alpha/design/components/checkbox.md
  website/versioned_docs/version-0.1.0-alpha/design/components/confirm-dialog.md
  website/versioned_docs/version-0.1.0-alpha/design/components/form-control.md
  website/versioned_docs/version-0.1.0-alpha/design/components/input.md
  website/versioned_docs/version-0.1.0-alpha/design/components/lists.md
  website/versioned_docs/version-0.1.0-alpha/design/components/menu.md
  website/versioned_docs/version-0.1.0-alpha/design/components/modal.md
  website/versioned_docs/version-0.1.0-alpha/design/components/pagination.md
  website/versioned_docs/version-0.1.0-alpha/design/components/radio.md
  website/versioned_docs/version-0.1.0-alpha/design/components/select.md
  website/versioned_docs/version-0.1.0-alpha/design/components/switch.md
  website/versioned_docs/version-0.1.0-alpha/design/content/_category_.yml
  website/versioned_docs/version-0.1.0-alpha/design/content/grammar.md
  website/versioned_docs/version-0.1.0-alpha/design/foundations/_category_.yml
  website/versioned_docs/version-0.1.0-alpha/design/foundations/color.mdx
  website/versioned_docs/version-0.1.0-alpha/start/get-started.md
Labels: documentation, design

#796 docs: added table page
  website/docs/design/components/table.md
Labels: documentation, design

#797 feat(hs): add TS types to exports declaration
  packages/headless-styles/package.json
  packages/headless-styles/rollup.config.mjs
  packages/headless-styles/tsconfig.json
Labels: enhancement

#800 Feat/713 popover flags
  packages/shared/src/featureFlags.ts
  packages/shared/src/index.ts
  packages/shared/tests/flags/experimental.test.ts
Labels: enhancement

#807 feat: added 3 icons to common actions
  packages/icons/src/common-actions/danger-diamond-filled.svg
  packages/icons/src/common-actions/danger-diamond.svg
  packages/icons/src/common-actions/info-circle-filled.svg
Labels: enhancement

#815 docs(dev): update ConfirmDialog HS API
  .pnp.cjs
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-29ec4f-d2ecbff0f2-fc42446242.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-b82bba-01e8c8d7f0-c32ab192fa.zip
  website/docs/development/headless-styles/ConfirmDialog.mdx
  website/src/components/ConfirmDialog/BasicConfirmDialog.preview.js
  website/src/components/ConfirmDialog/ConfirmDialog.js
  yarn.lock
Labels: documentation

#817 docs(dev): add disclaimers section to components.mdx
  website/docs/development/headless-styles/FormControl.mdx
  website/docs/development/headless-styles/customization/components.mdx
Labels: documentation

#804 docs: added tabs page
  website/docs/design/components/tabs.md
Labels: documentation, design

#824 docs: added tag page
  website/docs/design/components/tag.md
Labels: documentation, design

#827 docs: add tooltip page
  website/docs/design/components/tooltip.md
Labels: documentation, design

#831 fix(hs): fine tune styling for Beta
  packages/headless-styles/sandbox/src/components/Input.jsx
  packages/headless-styles/sandbox/src/components/Select.jsx
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.module.css
  packages/headless-styles/src/components/ErrorMessage/errorMessageJS.ts
  packages/headless-styles/src/components/ErrorMessage/generated/errorMessageCSS.module.ts
  packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.module.css
  packages/headless-styles/src/components/FieldMessage/fieldMessageJS.ts
  packages/headless-styles/src/components/FieldMessage/generated/fieldMessageCSS.module.ts
Labels: bug

#832 feat: remove popover feature flag
  packages/shared/src/featureFlags.ts
  packages/shared/src/index.ts
  packages/shared/tests/flags/experimental.test.ts
Labels: enhancement

#835 fix(headless-styles): correct classname reference in tooltip JS posit…
  packages/headless-styles/src/components/Tooltip/tooltipJS.ts
Labels: bug

#836 build: update versions for beta release
  versions.mjs
Labels: enhancement

#819 Narrow types for `createJSProps` and `createCSSObj` return values
  packages/headless-styles/src/utils/helpers.ts
Labels: enhancement

#843 docs(dev): update Menu API to match current Next version
  .pnp.cjs
  .yarn/cache/@pluralsight-headless-styles-npm-0.1.2-beta-0d6dcd-4fbebf0ecc-ed3484e00d.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.2.0-rc-d9f115-ac8cd0f23c-56117fd08f.zip
  website/docs/development/headless-styles/Menu.mdx
  website/src/components/Menu/BasicMenu.preview.js
  website/src/components/Menu/Menu.js
  website/src/components/Menu/SubmenuExample.preview.js
  website/src/theme/ReactLiveScope/index.js
  yarn.lock
Labels: documentation

#845 docs: added popover page
  website/docs/design/components/popover.md
Labels: documentation, design

#855 build: update versions to 0.3.1
  versions.mjs
Labels: dependencies

#854 docs: added progress page
  website/docs/design/components/progress.md
Labels: documentation, design

#858 docs(blog): add beta release notes
  website/blog/2022-011-30-dev-beta/index.md
Labels: documentation

#859 docs: grammer update on beta annoucement
  website/blog/2022-011-30-dev-beta/index.md
Labels: documentation
