Repository pluralsight/pando, pull requests merged in 2022-08, with the labels that each got.

#481 feat(headless-styles): add Chakra theme for Link
  packages/headless-styles/src/chakra.ts
  packages/headless-styles/src/components/TextLink/chakraTextLink.ts
  packages/headless-styles/src/components/TextLink/shared.ts
Labels: enhancement

#492 feat(tokens): add subpath exports & commonJS support
  packages/design-tokens/data.config.cjs
  packages/design-tokens/package.json
  packages/design-tokens/utils/formats/dataSources.cjs
  packages/design-tokens/utils/vars.cjs
Labels: enhancement

#494 fix(tokens): make light theme match dark
  packages/design-tokens/tokens/public/light.yaml
Labels: bug

#510 chore(website): update HS dependency - breaks examples
  .pnp.cjs
  .yarn/cache/@pluralsight-headless-styles-npm-0.0.0-experimental-30088c-20220809-b9e8bf1568-c12bd25488.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.0.0-experimental-500ff4-20220822-28194109b5-23a2611c19.zip
  yarn.lock
Labels: dependencies

#516 refactor(headless): add ButtonJS API & tests
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/Button.jsx
  packages/headless-styles/src/components/Button/buttonJS.ts
  packages/headless-styles/src/components/Button/types.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/tests/button/buttonCSS.test.ts
  packages/headless-styles/tests/button/buttonJS.test.ts
Labels: enhancement

#518 feat(headless-styles): update checked font color to new token value
  packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
  packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
Labels: enhancement

#539 feat(design-tokens): update base list typography styles
  packages/design-tokens/styles/base.css
Labels: enhancement
