Repository pluralsight/pando, pull requests merged in 2022-09, with the labels that each got.

#546 Revert "feat(design-tokens): update base list typography styles"
  packages/design-tokens/styles/base.css
Labels: bug

#554 build: convert shared to public package
  .pnp.cjs
  packages/headless-styles/package.json
  packages/headless-styles/src/components/Menu/menuCSS.ts
  packages/headless-styles/src/globalJS.d.ts
  packages/shared/package.json
  versions.mjs
  yarn.lock
Labels: enhancement

#557 ci: add dynamic hs package update
  .github/workflows/publish_experimental_release.yml
  .github/workflows/publish_next_release.yml
Labels: enhancement

#564 ci: move update:deps to publish action
  .github/workflows/publish_experimental_release.yml
  .github/workflows/publish_next_release.yml
  .pnp.cjs
  .yarn/cache/@pluralsight-shared-npm-0.1.0-experimental-67106c-20220907-daf3a88a2d-c134ca456c.zip
  .yarn/cache/@pluralsight-shared-npm-0.1.0-experimental-8be402-20220907-5bbeffb5bf-893236be96.zip
  packages/headless-styles/package.json
  yarn.lock
Labels: github_actions

#570 ci: add version and env.release_channel to stable script
  .github/workflows/publish_stable_releases.yml
Labels: github_actions

#571 feat(shared): add all flag options in featureFlags
  packages/shared/src/featureFlags.js
Labels: enhancement

#572 feat(headless-styles): return null instead of props for disabled feature
  packages/headless-styles/src/components/Menu/menuCSS.ts
  packages/headless-styles/src/components/Menu/menuJS.ts
Labels: enhancement

#586 docs: alpha release notes
  website/blog/2022-09-14-dev-alpha/index.md
Labels: documentation

#588 Feat/580 icons ts support
  packages/icons/package.json
Labels: enhancement

#589 docs(headless-styles): add descriptions of getMenuProps arguments
  website/docs/development/headless-styles/Menu.mdx
Labels: documentation

#590 feat(shared): add preloadImgHook to flags
  packages/shared/src/featureFlags.js
Labels: enhancement

#594 Fix/shared config a
  packages/shared/tsconfig.build.json
  packages/shared/tsconfig.json
Labels: bug

#597 fix(website): update selectors to account for production class names
  website/src/css/custom.css
Labels: bug

#602 fix(shared): use explicit exports instead of wildcard
  packages/shared/src/index.ts
Labels: bug

#610 build: up react to latest in all workspaces
  .pnp.cjs
  .yarn/cache/@types-react-npm-18.0.20-064ea90ef1-f67f5b16ef.zip
  .yarn/cache/react-dom-npm-18.0.0-d6a12fba32-dd0ba9f2f3.zip
  .yarn/cache/react-npm-18.0.0-fdbcb4c477-293020b965.zip
  .yarn/cache/scheduler-npm-0.21.0-9a906f4833-4f82850760.zip
  packages/headless-styles/package.json
  packages/headless-styles/sandbox/package.json
  packages/icons/package.json
  packages/react-utils/package.json
  packages/react-utils/src/hooks/useFocusTrap.ts
  packages/react-utils/tests/hooks/useFocusTrap.test.tsx
  website/package.json
  yarn.lock
Labels: dependencies

#617 fix(shared): add tabs flag to export list
  packages/shared/src/index.ts
Labels: bug

#620 feat(react-utils): add useHook flag
  packages/shared/src/featureFlags.ts
  packages/shared/src/index.ts
  packages/shared/tests/flags/experimental.test.ts
  packages/shared/tests/flags/next.test.ts
Labels: enhancement

#626 Feat/502 tab focus
  packages/headless-styles/src/components/Tab/generated/tabCSS.module.ts
  packages/headless-styles/src/components/Tab/tabCSS.module.css
Labels: enhancement

#633 fix(react-utils): correct spelling error in return props of useFocusTrap
  packages/headless-styles/sandbox/src/components/ConfirmDialog.jsx
  packages/react-utils/src/hooks/useFocusTrap.ts
  packages/react-utils/tests/hooks/useFocusTrap.test.tsx
Labels: bug

#638 chore: up shared in HS & RU
  .pnp.cjs
  .yarn/cache/@pluralsight-shared-npm-0.1.0-experimental-a41597-20220928-ea3b5a066d-202df02383.zip
  .yarn/cache/@pluralsight-shared-npm-0.1.0-experimental-c80546-20220928-d74256e356-1f838c5973.zip
  yarn.lock
Labels: dependencies
