Repository pluralsight/pando, pull requests merged in 2022-04, with the labels that each got.

#148 fixed typo
  website/docs/development/getting-started/migration.md
Labels: documentation

#149 Docs/icons refine
  website/docs/development/packages/icons/usage.mdx
  website/docs/development/packages/icons/usage_mobile.md
  website/src/components/Icons/BasicIcon.preview.js
Labels: documentation

#153 fix(hs): add correct height to base chakra class in Button
  packages/headless-styles/src/components/Button/buttonCSS.module.css
Labels: bug

#155 docs: add custom theming section to colors.mdx
  website/docs/development/packages/tokens/colors.mdx
Labels: documentation

#166 docs: update gtag to use measurement ID vs. stream ID
  website/docusaurus.config.js
Labels: bug, documentation

#170 refactor(tokens): update build to use ES module wrapper Node strategy
  .stylelintignore
  packages/design-tokens/config.cjs
  packages/design-tokens/flow.config.cjs
  packages/design-tokens/mobile.config.cjs
  packages/design-tokens/package.json
  packages/design-tokens/utils/filters/baseFilter.cjs
  packages/design-tokens/utils/filters/jsFilter.cjs
  packages/design-tokens/utils/vars.cjs
Labels: enhancement

#177 feat(hs): update getButtonProps to use rawClass for Svelte apps
  .vscode/extensions.json
  packages/headless-styles/src/components/Button/buttonCSS.ts
  packages/headless-styles/src/components/Button/types.ts
  packages/headless-styles/tests/button/buttonCSS.test.ts
  website/docs/development/packages/headless-styles/Button.mdx
Labels: documentation, enhancement

#178 docs: update LiveExamplesTabs to use Svelte icon
  website/src/components/LiveExampleTabs/LiveExampleTabs.js
  website/src/components/LiveExampleTabs/LiveExampleTabs.module.css
Labels: documentation, enhancement

#183 feat(hs): add badgeJS and helpers
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/Badge.jsx
  packages/headless-styles/sandbox/src/components/Button.jsx
  packages/headless-styles/src/components/Badge/badgeJS.ts
  packages/headless-styles/src/components/Badge/generated/badgeCSS.module.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/src/utils/helpers.ts
  packages/headless-styles/tests/badge/badgeJS.test.ts
  packages/headless-styles/tests/utils/helpers.test.ts
Labels: enhancement

#185 feat(hs): update Badge to include MUI related styles
  packages/headless-styles/src/components/Badge/badgeCSS.module.css
  packages/headless-styles/src/components/Badge/generated/badgeCSS.module.ts
Labels: enhancement

#186 feat(hs): add MUI label override export
  packages/headless-styles/src/components/Badge/badgeJS.ts
  packages/headless-styles/src/components/Badge/shared.ts
  packages/headless-styles/src/components/Badge/types.ts
Labels: enhancement

#187 feat(hs): add muiLabelOverride to main exports
  packages/headless-styles/src/index.ts
Labels: enhancement

#189 feat(icons): optimize and format icons via svgo
  .pnp.cjs
  .yarn/cache/@types-svgo-npm-2.6.3-4686f3b65b-d72714e565.zip
  packages/icons/package.json
  packages/icons/src/utils/addAriaLabel.cjs
  packages/icons/svgo.config.cjs
  packages/icons/tests/utils/addAriaLabel.test.js
  yarn.lock
Labels: enhancement

#192 fix(hs): remove unnecessary padding prop in muiLabelOverride
  packages/headless-styles/src/components/Badge/badgeJS.ts
Labels: bug

#201 fix(hs): temporarily remove type "module" in package.json
  packages/headless-styles/package.json
Labels: bug

#206 feat(icons): add audio-video source icons
  packages/icons/package.json
  packages/icons/src/arrows/arrow-down-right.svg
  packages/icons/src/arrows/arrow-down.svg
  packages/icons/src/arrows/arrow-left.svg
  packages/icons/src/arrows/arrow-right.svg
  packages/icons/src/arrows/arrow-up-right.svg
  packages/icons/src/arrows/arrow-up.svg
  packages/icons/src/arrows/caret-down.svg
  packages/icons/src/arrows/caret-left.svg
  packages/icons/src/arrows/caret-right.svg
  packages/icons/src/arrows/caret-up.svg
  packages/icons/src/arrows/chevron-down.svg
  packages/icons/src/arrows/chevron-left.svg
  packages/icons/src/arrows/chevron-right.svg
  packages/icons/src/arrows/chevron-up.svg
  packages/icons/src/audio-video/close-captioned-filled.svg
  packages/icons/src/audio-video/close-captioned.svg
  packages/icons/src/audio-video/fullscreen-exit.svg
  packages/icons/src/audio-video/fullscreen.svg
  packages/icons/src/audio-video/microphone.svg
  packages/icons/src/audio-video/next.svg
  packages/icons/src/audio-video/pause.svg
  packages/icons/src/audio-video/play-circle-filled.svg
  packages/icons/src/audio-video/play-circle.svg
  packages/icons/src/audio-video/play.svg
  packages/icons/src/audio-video/podcast.svg
  packages/icons/src/audio-video/previous.svg
  packages/icons/src/audio-video/skip-backward.svg
  packages/icons/src/audio-video/skip-forward.svg
  packages/icons/src/audio-video/transcript.svg
  packages/icons/src/audio-video/video.svg
  packages/icons/src/audio-video/volume-high.svg
  packages/icons/src/audio-video/volume-low.svg
  packages/icons/src/audio-video/volume-medium.svg
  packages/icons/src/audio-video/volume-off.svg
  packages/icons/svgo.config.cjs
  packages/icons/tests/utils/addAriaLabel.test.js
  packages/icons/utils/addAriaLabel.cjs
Labels: enhancement

#207 feat(icons): add source icons for brands
  packages/icons/src/brands/box.svg
  packages/icons/src/brands/dribbble.svg
  packages/icons/src/brands/dropbox.svg
  packages/icons/src/brands/facebook-alt.svg
  packages/icons/src/brands/facebook.svg
  packages/icons/src/brands/github.svg
  packages/icons/src/brands/google-drive.svg
  packages/icons/src/brands/linkedin-alt.svg
  packages/icons/src/brands/linkedin.svg
  packages/icons/src/brands/medium-alt.svg
  packages/icons/src/brands/medium.svg
  packages/icons/src/brands/npm.svg
  packages/icons/src/brands/pluralsight.svg
  packages/icons/src/brands/slack.svg
  packages/icons/src/brands/stack-overflow.svg
  packages/icons/src/brands/twitter.svg
Labels: enhancement

#208 feat(icons): add common-action source icons (part 1)
  packages/icons/src/common-actions/bookmark-filled.svg
  packages/icons/src/common-actions/bookmark.svg
  packages/icons/src/common-actions/briefcase.svg
  packages/icons/src/common-actions/building.svg
  packages/icons/src/common-actions/calendar.svg
  packages/icons/src/common-actions/challenge.svg
  packages/icons/src/common-actions/clock-warning.svg
  packages/icons/src/common-actions/clock.svg
  packages/icons/src/common-actions/cloud-off.svg
  packages/icons/src/common-actions/cloud.svg
  packages/icons/src/common-actions/ellipsis-horizontal.svg
  packages/icons/src/common-actions/eye-off.svg
  packages/icons/src/common-actions/eye.svg
  packages/icons/src/common-actions/globe.svg
  packages/icons/src/common-actions/hand.svg
  packages/icons/src/common-actions/help-circle-filled.svg
  packages/icons/src/common-actions/help-circle.svg
  packages/icons/src/common-actions/info-circle.svg
  packages/icons/src/common-actions/interactive.svg
  packages/icons/src/common-actions/location.svg
  packages/icons/src/common-actions/lock-filled.svg
  packages/icons/src/common-actions/lock.svg
  packages/icons/src/common-actions/megaphone.svg
  packages/icons/src/common-actions/move.svg
  packages/icons/src/common-actions/note.svg
  packages/icons/src/common-actions/objective.svg
Labels: enhancement

#213 feat(icons): second half of common-actions icon set
  packages/icons/src/common-actions/monitor.svg
  packages/icons/src/common-actions/org-chart.svg
  packages/icons/src/common-actions/phone-down.svg
  packages/icons/src/common-actions/phone.svg
  packages/icons/src/common-actions/placeholder.svg
  packages/icons/src/common-actions/project.svg
  packages/icons/src/common-actions/q-and-a.svg
  packages/icons/src/common-actions/report.svg
  packages/icons/src/common-actions/scope.svg
  packages/icons/src/common-actions/signout.svg
  packages/icons/src/common-actions/sync.svg
  packages/icons/src/common-actions/tag-management.svg
  packages/icons/src/common-actions/tag.svg
  packages/icons/src/common-actions/test.svg
  packages/icons/src/common-actions/theme.svg
  packages/icons/src/common-actions/upload.svg
  packages/icons/src/common-actions/warning-filled.svg
  packages/icons/src/common-actions/warning-triangle-filled.svg
  packages/icons/src/common-actions/warning-triangle.svg
  packages/icons/src/common-actions/warning.svg
  packages/icons/src/common-actions/windows.svg
Labels: enhancement

#215 feat(icons): revised arrow icons with full-box sizing
  packages/icons/src/arrows/arrow-down-right.svg
  packages/icons/src/arrows/arrow-down.svg
  packages/icons/src/arrows/arrow-left.svg
  packages/icons/src/arrows/arrow-right.svg
  packages/icons/src/arrows/arrow-up-right.svg
  packages/icons/src/arrows/arrow-up.svg
  packages/icons/src/arrows/caret-down.svg
  packages/icons/src/arrows/caret-left.svg
  packages/icons/src/arrows/caret-right.svg
  packages/icons/src/arrows/caret-up.svg
  packages/icons/src/arrows/chevron-down.svg
  packages/icons/src/arrows/chevron-left.svg
  packages/icons/src/arrows/chevron-right.svg
  packages/icons/src/arrows/chevron-up.svg
Labels: enhancement

#216 feat(icons): resize a/v icons, also adding/renaming a few that were m…
  packages/icons/src/audio-video/close-captioned-filled.svg
  packages/icons/src/audio-video/close-captioned.svg
  packages/icons/src/audio-video/closed-caption-filled.svg
  packages/icons/src/audio-video/closed-caption.svg
  packages/icons/src/audio-video/fullscreen-exit.svg
  packages/icons/src/audio-video/fullscreen.svg
  packages/icons/src/audio-video/microphone.svg
  packages/icons/src/audio-video/next.svg
  packages/icons/src/audio-video/pause-circle-filled.svg
  packages/icons/src/audio-video/pause-circle.svg
  packages/icons/src/audio-video/pause.svg
  packages/icons/src/audio-video/play-circle-filled.svg
  packages/icons/src/audio-video/play-circle.svg
  packages/icons/src/audio-video/play.svg
  packages/icons/src/audio-video/podcast.svg
  packages/icons/src/audio-video/previous.svg
  packages/icons/src/audio-video/screenshare.svg
  packages/icons/src/audio-video/skip-backward.svg
  packages/icons/src/audio-video/skip-forward.svg
  packages/icons/src/audio-video/transcript.svg
  packages/icons/src/audio-video/video.svg
  packages/icons/src/audio-video/volume-high.svg
  packages/icons/src/audio-video/volume-low.svg
  packages/icons/src/audio-video/volume-medium.svg
  packages/icons/src/audio-video/volume-off.svg
Labels: enhancement

#217 feat(icons): resize brand icons to fill view box
  packages/icons/src/brands/box.svg
  packages/icons/src/brands/dribbble.svg
  packages/icons/src/brands/dropbox.svg
  packages/icons/src/brands/facebook-alt.svg
  packages/icons/src/brands/facebook.svg
  packages/icons/src/brands/github.svg
  packages/icons/src/brands/google-drive.svg
  packages/icons/src/brands/linkedin-alt.svg
  packages/icons/src/brands/linkedin.svg
  packages/icons/src/brands/medium-alt.svg
  packages/icons/src/brands/medium.svg
  packages/icons/src/brands/npm.svg
  packages/icons/src/brands/pluralsight.svg
  packages/icons/src/brands/slack.svg
  packages/icons/src/brands/stack-overflow.svg
  packages/icons/src/brands/twitter.svg
Labels: enhancement

#222 feat(icons): add communication icons
  packages/icons/src/communication/at-symbol.svg
  packages/icons/src/communication/chat-message-filled.svg
  packages/icons/src/communication/chat-message-lines-filled.svg
  packages/icons/src/communication/chat-message-lines.svg
  packages/icons/src/communication/chat-message.svg
  packages/icons/src/communication/connection-warning.svg
  packages/icons/src/communication/envelope-arrow.svg
  packages/icons/src/communication/envelope.svg
  packages/icons/src/communication/notifications-active.svg
  packages/icons/src/communication/notifications.svg
Labels: enhancement

#225 Feat/icons alignment
  packages/icons/src/audio-video/volume-high.svg
  packages/icons/src/audio-video/volume-low.svg
  packages/icons/src/audio-video/volume-medium.svg
  packages/icons/src/audio-video/volume-off.svg
  packages/icons/src/common-actions/cloud-off.svg
  packages/icons/src/common-actions/cloud.svg
  packages/icons/src/common-actions/eye-off.svg
  packages/icons/src/common-actions/eye.svg
Labels: enhancement
