Repository pluralsight/pando, pull requests merged in 2022-10, with the labels that each got.

#644 fix(react-utils): prevent default when esc is pressed in useEscToClos…
  packages/react-utils/src/hooks/useEscToClose.ts
Labels: bug

#650 docs(dev): fix type in useTabs.mdx
  website/docs/development/react-utils/use-tabs.mdx
Labels: documentation

#652 feat(shared): promote modal flag to 'next'
  packages/shared/src/featureFlags.ts
  packages/shared/tests/flags/experimental.test.ts
  packages/shared/tests/flags/next.test.ts
Labels: enhancement

#664 test(headless-styles): fix capitalization of onKeyDown for modal sandbox
  packages/headless-styles/sandbox/src/components/Modal.jsx
Labels: bug

#668 docs: update normalize links for new build path
  website/docs/development/getting-started/installation.md
  website/docs/development/getting-started/migration.md
  website/src/css/custom.css
Labels: bug

#680 docs: update design-tokens to use specific versions
  website/docs/development/getting-started/installation.md
  website/versioned_docs/version-0.1.0-alpha/development/getting-started/installation.md
Labels: documentation

#682 feat(headless-styles): upgrade tooltip to next channel
  packages/headless-styles/index.stable.js
Labels: enhancement

#685 fix(headless-styles): add missing bracket to inputJS iconWrapper output
  packages/headless-styles/src/components/Input/inputJS.ts
Labels: bug

#686 fix(hs): update rollup to use entry paths used in npm
  packages/headless-styles/rollup.config.mjs
Labels: bug

#688 feat(tokens): update base to set bgc and color properties
  packages/design-tokens/normalize.scss
  packages/design-tokens/styles/base.css
  versions.mjs
Labels: enhancement

#689 build(react-utils): add rollup
  .gitignore
  .pnp.cjs
  .yarn/cache/@rollup-plugin-commonjs-npm-23.0.0-8c352b2407-a8b23ae4c6.zip
  .yarn/cache/glob-npm-8.0.3-750f909025-50bcdea19d.zip
  .yarn/cache/is-reference-npm-1.2.1-87ca1743c8-e7b48149f8.zip
  packages/react-utils/package.json
  packages/react-utils/rollup.config.mjs
  packages/react-utils/tsconfig.browser.json
  yarn.lock
Labels: enhancement

#699 feat(hs): promote table to stable release
  .eslintignore
  eslint.config.js
  packages/headless-styles/index.experimental.js
  packages/headless-styles/index.stable.js
  packages/shared/src/featureFlags.ts
  packages/shared/tests/flags/experimental.test.ts
  packages/shared/tests/flags/stable.test.ts
Labels: enhancement

#700 feat(hs): update ChakraTable styles
  packages/headless-styles/src/components/Table/chakraTable.ts
Labels: enhancement

#599 docs: add color page
  website/docs/design/color.mdx
  website/docs/start/get-started.md
  website/docusaurus.config.js
  website/versioned_docs/version-0.1.0-alpha/design/color.md
  website/versioned_docs/version-0.1.0-alpha/design/intro.md
  website/versioned_docs/version-0.1.0-alpha/start/get-started.md
Labels: documentation

#705 feat(headless-styles): promote Select to stable
  packages/headless-styles/index.stable.js
  packages/shared/src/featureFlags.ts
  packages/shared/tests/flags/experimental.test.ts
  packages/shared/tests/flags/stable.test.ts
Labels: enhancement

#707 fix(headless-styles): remove multiple select styles from standard select
  packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
  packages/headless-styles/src/components/Select/selectCSS.module.css
Labels: enhancement
