Repository pluralsight/pando, pull requests merged in 2022-05, with the labels that each got.

#226 feat(icons): add editor icons
  packages/icons/src/editor/article.svg
  packages/icons/src/editor/code-branded.svg
  packages/icons/src/editor/code.svg
  packages/icons/src/editor/list-bullets.svg
  packages/icons/src/editor/redo.svg
  packages/icons/src/editor/undo.svg
Labels: enhancement

#228 Feat/icons social
  packages/icons/src/brands/ilx.svg
  packages/icons/src/brands/labs.svg
  packages/icons/src/brands/role-iq.svg
  packages/icons/src/brands/skill-iq.svg
  packages/icons/src/social/people.svg
  packages/icons/src/social/person-add.svg
  packages/icons/src/social/person.svg
  packages/icons/src/social/share.svg
Labels: enhancement

#229 feat(icons): add ui-action source icons
  packages/icons/src/ui-actions/channel-add.svg
  packages/icons/src/ui-actions/check-circle-filled.svg
  packages/icons/src/ui-actions/check-circle.svg
  packages/icons/src/ui-actions/check.svg
  packages/icons/src/ui-actions/close.svg
  packages/icons/src/ui-actions/copy.svg
  packages/icons/src/ui-actions/delete.svg
  packages/icons/src/ui-actions/download.svg
  packages/icons/src/ui-actions/file.svg
  packages/icons/src/ui-actions/filter.svg
  packages/icons/src/ui-actions/folder.svg
  packages/icons/src/ui-actions/gear.svg
  packages/icons/src/ui-actions/not-allowed.svg
  packages/icons/src/ui-actions/paperclip.svg
  packages/icons/src/ui-actions/pencil.svg
  packages/icons/src/ui-actions/plus-circle-filled.svg
  packages/icons/src/ui-actions/plus-circle.svg
  packages/icons/src/ui-actions/plus.svg
  packages/icons/src/ui-actions/search.svg
  packages/icons/src/ui-actions/sort-ascending.svg
  packages/icons/src/ui-actions/sort-descending.svg
  packages/icons/src/ui-actions/sort.svg
  packages/icons/src/ui-actions/star-filled.svg
  packages/icons/src/ui-actions/star.svg
  packages/icons/src/ui-actions/thumb-down-filled.svg
  packages/icons/src/ui-actions/thumb-down.svg
  packages/icons/src/ui-actions/thumb-up-filled.svg
  packages/icons/src/ui-actions/thumb-up.svg
  packages/icons/src/ui-actions/x-circle-filled.svg
  packages/icons/src/ui-actions/x-circle.svg
Labels: enhancement

#232 feat(icons): add svgo plugin to square viewBox attribute
  packages/icons/package.json
  packages/icons/svgo.config.cjs
  packages/icons/tests/utils/squareViewBox.test.js
  packages/icons/utils/squareViewBox.cjs
Labels: enhancement

#233 feat(hs): add muiReset for Progress
  packages/headless-styles/src/components/Progress/progressJS.ts
  packages/headless-styles/src/index.ts
Labels: enhancement

#240 Feat/icons react
  .pnp.cjs
  packages/icons/package.json
  packages/icons/svgr.config.cjs
  packages/icons/tsconfig.cjs.json
  packages/icons/tsconfig.json
  packages/icons/utils/reactPostbuild.mjs
  packages/icons/utils/reactTemplate.cjs
  packages/icons/utils/svgToReact.mjs
  yarn.lock
Labels: enhancement

#247 feat(icons): generate svelte icons
  .pnp.cjs
  .yarn/cache/@types-fs-extra-npm-4.0.12-ef65781a9b-6a14044be3.zip
  .yarn/cache/svelte-npm-3.48.0-4bfc3244b5-d72587582b.zip
  packages/icons/package.json
  packages/icons/tsconfig.svelte.json
  packages/icons/utils/reactPostbuild.mjs
  packages/icons/utils/svgToSvelte.mjs
  yarn.lock
Labels: enhancement

#250 docs(icons): add links to codesandbox examples
  website/docs/development/packages/icons/usage.mdx
Labels: documentation

#251 feat(headless-styles): add getIconProps
  packages/headless-styles/src/components/Icon/iconCSS.module.css
  packages/headless-styles/src/components/Icon/iconCSS.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/components/Icon/types.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/tests/icon/iconCSS.test.ts
Labels: enhancement

#255 fix(headless-styles): rename icon size classes
  packages/headless-styles/src/components/Icon/iconCSS.module.css
  packages/headless-styles/src/components/Icon/iconCSS.ts
  packages/headless-styles/tests/icon/iconCSS.test.ts
Labels: bug

#262 fix(icons): fix tsconfig 'excludes' and merge svelte configs with the…
  packages/icons/package.json
  packages/icons/tsconfig.json
Labels: bug

#263 Docs/hs get js icon props
  website/docs/development/packages/headless-styles/Icon.mdx
  website/docs/development/packages/icons/usage.mdx
Labels: documentation

#271 docs(headless-styles): update available sizes
  website/docs/development/packages/headless-styles/Icon.mdx
  website/docs/development/packages/icons/usage.mdx
  website/src/components/Icons/BasicIcon.js
  website/src/components/Icons/IconSizes.js
  website/src/components/Icons/IconSizes.preview.js
Labels: documentation

#272 feat(icons): update arrow icons with design dimensions
  packages/icons/src/arrows/arrow-down-right.svg
  packages/icons/src/arrows/arrow-down.svg
  packages/icons/src/arrows/arrow-left.svg
  packages/icons/src/arrows/arrow-right.svg
  packages/icons/src/arrows/arrow-up-right.svg
  packages/icons/src/arrows/arrow-up.svg
  packages/icons/src/arrows/caret-down.svg
  packages/icons/src/arrows/caret-left.svg
  packages/icons/src/arrows/caret-right.svg
  packages/icons/src/arrows/caret-up.svg
  packages/icons/src/arrows/chevron-down.svg
  packages/icons/src/arrows/chevron-left.svg
  packages/icons/src/arrows/chevron-right.svg
  packages/icons/src/arrows/chevron-up.svg
Labels: enhancement

#274 feat(icons): update a/v icons with design dimensions
  packages/icons/src/audio-video/closed-caption-filled.svg
  packages/icons/src/audio-video/closed-caption.svg
  packages/icons/src/audio-video/fullscreen-exit.svg
  packages/icons/src/audio-video/fullscreen.svg
  packages/icons/src/audio-video/microphone.svg
  packages/icons/src/audio-video/next.svg
  packages/icons/src/audio-video/pause-circle-filled.svg
  packages/icons/src/audio-video/pause-circle.svg
  packages/icons/src/audio-video/pause.svg
  packages/icons/src/audio-video/play-circle-filled.svg
  packages/icons/src/audio-video/play-circle.svg
  packages/icons/src/audio-video/play.svg
  packages/icons/src/audio-video/podcast.svg
  packages/icons/src/audio-video/previous.svg
  packages/icons/src/audio-video/screenshare.svg
  packages/icons/src/audio-video/skip-backward.svg
  packages/icons/src/audio-video/skip-forward.svg
  packages/icons/src/audio-video/transcript.svg
  packages/icons/src/audio-video/video.svg
  packages/icons/src/audio-video/volume-high.svg
  packages/icons/src/audio-video/volume-low.svg
  packages/icons/src/audio-video/volume-medium.svg
  packages/icons/src/audio-video/volume-off.svg
Labels: enhancement

#275 feat(icons): update brand icons with design dimensions
  packages/icons/src/brands/box.svg
  packages/icons/src/brands/dribbble.svg
  packages/icons/src/brands/dropbox.svg
  packages/icons/src/brands/facebook-alt.svg
  packages/icons/src/brands/facebook.svg
  packages/icons/src/brands/github.svg
  packages/icons/src/brands/google-drive.svg
  packages/icons/src/brands/ilx.svg
  packages/icons/src/brands/labs.svg
  packages/icons/src/brands/linkedin-alt.svg
  packages/icons/src/brands/linkedin.svg
  packages/icons/src/brands/medium-alt.svg
  packages/icons/src/brands/medium.svg
  packages/icons/src/brands/npm.svg
  packages/icons/src/brands/pluralsight.svg
  packages/icons/src/brands/role-iq.svg
  packages/icons/src/brands/skill-iq.svg
  packages/icons/src/brands/slack.svg
  packages/icons/src/brands/stack-overflow.svg
  packages/icons/src/brands/twitter.svg
Labels: enhancement

#277 feat(icons): update common action icons (1 of 2) with design dimensions
  packages/icons/src/common-actions/bookmark-filled.svg
  packages/icons/src/common-actions/bookmark.svg
  packages/icons/src/common-actions/briefcase.svg
  packages/icons/src/common-actions/building.svg
  packages/icons/src/common-actions/calendar.svg
  packages/icons/src/common-actions/challenge.svg
  packages/icons/src/common-actions/clock-warning.svg
  packages/icons/src/common-actions/clock.svg
  packages/icons/src/common-actions/cloud-off.svg
  packages/icons/src/common-actions/cloud.svg
  packages/icons/src/common-actions/ellipsis-horizontal.svg
  packages/icons/src/common-actions/eye-off.svg
  packages/icons/src/common-actions/eye.svg
  packages/icons/src/common-actions/globe.svg
  packages/icons/src/common-actions/hand.svg
  packages/icons/src/common-actions/help-circle-filled.svg
  packages/icons/src/common-actions/help-circle.svg
  packages/icons/src/common-actions/info-circle.svg
  packages/icons/src/common-actions/interactive.svg
  packages/icons/src/common-actions/location.svg
  packages/icons/src/common-actions/lock-filled.svg
  packages/icons/src/common-actions/lock.svg
Labels: enhancement

#278 feat(icons): update common action icons (2 of 2) with design dimensions
  packages/icons/src/common-actions/megaphone.svg
  packages/icons/src/common-actions/monitor.svg
  packages/icons/src/common-actions/move.svg
  packages/icons/src/common-actions/note.svg
  packages/icons/src/common-actions/objective.svg
  packages/icons/src/common-actions/org-chart.svg
  packages/icons/src/common-actions/phone-down.svg
  packages/icons/src/common-actions/phone.svg
  packages/icons/src/common-actions/placeholder.svg
  packages/icons/src/common-actions/project.svg
  packages/icons/src/common-actions/q-and-a.svg
  packages/icons/src/common-actions/report.svg
  packages/icons/src/common-actions/scope.svg
  packages/icons/src/common-actions/signout.svg
  packages/icons/src/common-actions/sync.svg
  packages/icons/src/common-actions/tag-management.svg
  packages/icons/src/common-actions/tag.svg
  packages/icons/src/common-actions/test.svg
  packages/icons/src/common-actions/theme.svg
  packages/icons/src/common-actions/upload.svg
  packages/icons/src/common-actions/warning-filled.svg
  packages/icons/src/common-actions/warning-triangle-filled.svg
  packages/icons/src/common-actions/warning-triangle.svg
  packages/icons/src/common-actions/warning.svg
  packages/icons/src/common-actions/windows.svg
Labels: enhancement

#281 feat(icons): update editor and social icons with design dimensions
  packages/icons/src/editor/article.svg
  packages/icons/src/editor/code-branded.svg
  packages/icons/src/editor/code.svg
  packages/icons/src/editor/list-bullets.svg
  packages/icons/src/editor/redo.svg
  packages/icons/src/editor/undo.svg
  packages/icons/src/social/people.svg
  packages/icons/src/social/person-add.svg
  packages/icons/src/social/person.svg
  packages/icons/src/social/share.svg
Labels: enhancement

#282 feat(icons): update navigation icons with design dimensions
  packages/icons/src/navigation/account.svg
  packages/icons/src/navigation/browse.svg
  packages/icons/src/navigation/channel.svg
  packages/icons/src/navigation/dashboard.svg
  packages/icons/src/navigation/external-link.svg
  packages/icons/src/navigation/history.svg
  packages/icons/src/navigation/home-admin-tools.svg
  packages/icons/src/navigation/home-content-tools.svg
  packages/icons/src/navigation/home.svg
  packages/icons/src/navigation/link.svg
  packages/icons/src/navigation/log.svg
  packages/icons/src/navigation/menu-arrow-left.svg
  packages/icons/src/navigation/menu-arrow-right.svg
  packages/icons/src/navigation/menu.svg
  packages/icons/src/navigation/notebooks.svg
  packages/icons/src/navigation/path.svg
  packages/icons/src/navigation/rss.svg
  packages/icons/src/navigation/tag-assignments.svg
Labels: enhancement

#283 feat(icons): update ui-action icons with design dimensions
  packages/icons/src/ui-actions/channel-add.svg
  packages/icons/src/ui-actions/check-circle-filled.svg
  packages/icons/src/ui-actions/check-circle.svg
  packages/icons/src/ui-actions/check.svg
  packages/icons/src/ui-actions/close.svg
  packages/icons/src/ui-actions/copy.svg
  packages/icons/src/ui-actions/delete.svg
  packages/icons/src/ui-actions/download.svg
  packages/icons/src/ui-actions/file.svg
  packages/icons/src/ui-actions/filter.svg
  packages/icons/src/ui-actions/folder.svg
  packages/icons/src/ui-actions/gear.svg
  packages/icons/src/ui-actions/not-allowed.svg
  packages/icons/src/ui-actions/paperclip.svg
  packages/icons/src/ui-actions/pencil.svg
  packages/icons/src/ui-actions/plus-circle-filled.svg
  packages/icons/src/ui-actions/plus-circle.svg
  packages/icons/src/ui-actions/plus.svg
  packages/icons/src/ui-actions/search.svg
  packages/icons/src/ui-actions/sort-ascending.svg
  packages/icons/src/ui-actions/sort-descending.svg
  packages/icons/src/ui-actions/sort.svg
  packages/icons/src/ui-actions/star-filled.svg
  packages/icons/src/ui-actions/star.svg
  packages/icons/src/ui-actions/thumb-down-filled.svg
  packages/icons/src/ui-actions/thumb-down.svg
  packages/icons/src/ui-actions/thumb-up-filled.svg
  packages/icons/src/ui-actions/thumb-up.svg
  packages/icons/src/ui-actions/x-circle-filled.svg
  packages/icons/src/ui-actions/x-circle.svg
Labels: enhancement

#289 Feat/icons category indices
  packages/icons/package.json
  packages/icons/utils/postbuild.mjs
  packages/icons/utils/reactPostbuild.mjs
  packages/icons/utils/svgToReact.mjs
Labels: enhancement

#290 Docs/icon gallery
  .pnp.cjs
  .yarn/cache/@pluralsight-icons-npm-0.0.0-alpha-5fed0c-95e4679f20-b59d0a0681.zip
  .yarn/cache/@pluralsight-icons-npm-0.0.0-alpha-607d0e-3459e7a068-8af7f9aed1.zip
  .yarn/cache/@pluralsight-icons-npm-0.0.0-experimental-5fed0c-20220523-d03885de02-16bdf2555f.zip
  .yarn/cache/@pluralsight-icons-npm-0.0.0-experimental-b5da4d-20220512-c048486b68-31e43c7d70.zip
  packages/icons/utils/squareViewBox.cjs
  website/docs/development/packages/icons/iconsList.mdx
  website/docs/development/packages/icons/intro.md
  website/docs/development/packages/icons/usage.mdx
  website/docs/development/packages/icons/usage_mobile.md
  website/src/components/Icons/IconGallery.js
  website/src/components/Icons/IconGallery.module.css
  yarn.lock
Labels: enhancement

#299 fix(hs): add missing Switch styles to JS API
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/src/components/Switch/switchJS.ts
Labels: bug

#302 docs(dev): add missing sandbox links to Radio.mdx
  website/docs/development/packages/headless-styles/Radio.mdx
Labels: bug, documentation

#310 feat(hs): create ErrorMessage CSS API
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/ErrorMessage.jsx
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.module.css
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.ts
  packages/headless-styles/src/components/ErrorMessage/generated/errorMessageCSS.module.ts
  packages/headless-styles/src/components/ErrorMessage/shared.ts
  packages/headless-styles/src/components/ErrorMessage/types.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/tests/errorMessage/errorMessageCSS.test.ts
Labels: enhancement

#303 Feat/get icon button props
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/IconButton.jsx
  packages/headless-styles/src/components/Button/buttonCSS.module.css
  packages/headless-styles/src/components/Button/iconButtonCSS.ts
  packages/headless-styles/src/components/Button/shared.ts
  packages/headless-styles/src/components/Button/types.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/components/Icon/types.ts
  packages/headless-styles/src/components/types.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/src/utils/helpers.ts
  packages/headless-styles/tests/button/iconButtonCSS.test.ts
  packages/headless-styles/tests/icon/iconJS.test.ts
  packages/headless-styles/tests/utils/helpers.test.ts
Labels: enhancement
