Repository pluralsight/pando, pull requests merged in 2022-07, with the labels that each got.

#409 chore: fix spelling error in Icon.mdx code example
  website/docs/development/headless-styles/Icon.mdx
Labels: bug, documentation

#432 fix(headless-styles): add base hover decoration for tag
  packages/headless-styles/src/components/Tag/generated/tagCSS.module.ts
  packages/headless-styles/src/components/Tag/tagCSS.module.css
  packages/headless-styles/src/components/Tag/tagJS.ts
Labels: bug

#434 docs(hs): add z-index values to intro.mdx
  website/docs/development/headless-styles/intro.mdx
Labels: documentation

#438 feat(icons): update placeholder icon to latest design
  packages/icons/src/common-actions/placeholder.svg
Labels: enhancement

#448 feat(hs): add all closing options to AlertDialog.jsx example
  packages/headless-styles/sandbox/src/components/AlertDialog.jsx
Labels: enhancement

#461 feat(headless-styles): add Chakra theme for Avatar
  packages/headless-styles/src/chakra.ts
  packages/headless-styles/src/components/Avatar/chakraAvatar.ts
Labels: enhancement

#474 feat(react-utils): add useEscToClose API
  packages/react-utils/src/hooks/useEscToClose.ts
  packages/react-utils/src/index.ts
  packages/react-utils/tests/hooks/useEscToClose.test.tsx
Labels: enhancement
