Repository pluralsight/pando, pull requests merged in 2022-06, with the labels that each got.

#316 feat(tokens): add build-mobile to git
  packages/design-tokens/build-mobile/android/colors.xml
  packages/design-tokens/build-mobile/ios-swift/StyleDictionary.swift
  packages/design-tokens/build-mobile/ios-swift/StyleDictionaryColor.swift
  packages/design-tokens/build-mobile/ios/StyleDictionaryColor.h
  packages/design-tokens/build-mobile/ios/StyleDictionaryColor.m
  packages/design-tokens/mobile.config.cjs
Labels: enhancement

#321 fix(icons): mark React as peer dependency
  packages/icons/package.json
  yarn.lock
Labels: bug

#326 Refactor/hs icon a11y
  packages/headless-styles/src/components/Button/iconButtonCSS.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/components/Icon/types.ts
  packages/headless-styles/tests/button/iconButtonCSS.test.ts
  packages/headless-styles/tests/icon/iconCSS.test.ts
  packages/headless-styles/tests/icon/iconJS.test.ts
  website/docs/development/packages/headless-styles/Button.mdx
  website/docs/development/packages/headless-styles/Icon.mdx
Labels: enhancement

#329 docs(dev): update FormControl docs to include examples
  website/docs/development/packages/headless-styles/FormControl.mdx
  website/src/components/Container/Container.js
  website/src/components/FormControl/BasicFormControl.js
  website/src/components/FormControl/BasicFormControl.preview.js
  website/src/components/FormControl/ErrorFormControl.js
  website/src/components/FormControl/RadioGroup.js
  website/src/components/FormControl/RequiredFormControl.js
Labels: documentation

#331 refactor(headless-styles): use createClassProp for Badge API
  packages/headless-styles/src/components/Badge/badgeCSS.ts
  packages/headless-styles/src/components/Badge/shared.ts
  packages/headless-styles/src/components/Badge/types.ts
Labels: enhancement

#333 refactor(headless-styles): use createClassProp for Button
  packages/headless-styles/src/components/Button/buttonCSS.ts
  packages/headless-styles/tests/button/buttonCSS.test.ts
Labels: enhancement

#338 refactor(hs): cleanup iconButtonCSS.ts
  packages/headless-styles/sandbox/src/components/IconButton.jsx
  packages/headless-styles/src/components/Button/iconButtonCSS.ts
  packages/headless-styles/src/components/Button/shared.ts
Labels: enhancement

#346 feat(hs): add Field Message JS/Chakra API
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/FieldMessage.jsx
  packages/headless-styles/src/chakra.ts
  packages/headless-styles/src/components/FieldMessage/fieldMessageJS.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/tests/fieldMessage/fieldMessageCSS.test.ts
  packages/headless-styles/tests/fieldMessage/fieldMessageJS.test.ts
Labels: enhancement

#352 refactor(headless-styles): use class helper for icon api
  packages/headless-styles/src/components/Icon/iconCSS.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/components/Icon/types.ts
Labels: enhancement

#355 Refactor/class helper switch
  packages/headless-styles/src/components/Switch/shared.ts
  packages/headless-styles/src/components/Switch/switchCSS.ts
  packages/headless-styles/src/components/Switch/types.ts
Labels: enhancement

#354 refactor(headless-styles): use class helper for skeleton api
  packages/headless-styles/src/components/Skeleton/shared.ts
  packages/headless-styles/src/components/Skeleton/skeletonCSS.ts
  packages/headless-styles/src/components/Skeleton/types.ts
Labels: enhancement

#353 refactor(headless-styles): use class helper for progress api
  packages/headless-styles/src/components/Progress/progressCSS.ts
  packages/headless-styles/src/components/Progress/shared.ts
  packages/headless-styles/src/components/Progress/types.ts
Labels: enhancement

#360 docs: adapt favicon color based on user-selected color theme
  website/static/img/logo.svg
Labels: documentation

#361 fix(icons): do not remove xmlns from exported svgs
  packages/icons/svgo.config.cjs
Labels: bug

#370 feat(hs): add indeterminate option to Checkbox API
  .pnp.cjs
  .yarn/cache/@pluralsight-icons-npm-0.0.0-alpha-ec347e-8339513ea2-0ddf3c9c71.zip
  .yarn/cache/@pluralsight-icons-npm-0.0.0-experimental-43902d-20220614-47bf1bb065-038d13493f.zip
  .yarn/cache/@pluralsight-icons-npm-0.0.0-experimental-ec347e-20220602-70601fac30-c0dc211f99.zip
  packages/headless-styles/sandbox/package.json
  packages/headless-styles/sandbox/src/components/Checkbox.jsx
  packages/headless-styles/src/components/Checkbox/shared.ts
  packages/headless-styles/src/components/Checkbox/types.ts
  packages/headless-styles/tests/checkbox/checkboxCSS.test.ts
  yarn.lock
Labels: enhancement

#381 Docs/get icon string
  website/docs/development/icons/usage.mdx
Labels: documentation

#399 feat(headless-styles): add getDangerButtonWithIcon CSS API
  packages/headless-styles/sandbox/src/components/ButtonWithIcon.jsx
  packages/headless-styles/src/index.ts
  packages/headless-styles/tests/button/buttonWithIconCSS.test.ts
Labels: enhancement
