Repository pluralsight/pando, pull requests merged in 2022-01, with the labels that each got.

#45 [ci]: add contributing.yml
  .github/workflows/contributing.yml
Labels: enhancement

#47 ci: add pr_target to contributing.yml for forks
  .github/workflows/contributing.yml
  website/README.md
Labels: bug

#41 docs: fix typo in versioning page
  website/docs/development/discover-more/versions.md
Labels: documentation

#49 docs(dev): update Button API re f2 Flow feedback
  website/.yarn/.cache/webpack/client-development-en/0.pack
  website/.yarn/.cache/webpack/client-development-en/1.pack
  website/.yarn/.cache/webpack/client-development-en/10.pack
  website/.yarn/.cache/webpack/client-development-en/2.pack
  website/.yarn/.cache/webpack/client-development-en/3.pack
  website/.yarn/.cache/webpack/client-development-en/4.pack
  website/.yarn/.cache/webpack/client-development-en/5.pack
  website/.yarn/.cache/webpack/client-development-en/7.pack
  website/.yarn/.cache/webpack/client-development-en/9.pack
  website/.yarn/.cache/webpack/client-development-en/index.pack
  website/.yarn/.cache/webpack/client-development-en/index.pack.old
  website/docs/development/packages/components/Button.md
Labels: documentation
