Repository pluralsight/pando, pull requests merged in 2022-12, with the labels that each got.

#863 docs: added skeleton page
  website/docs/design/components/skeleton.md
Labels: documentation, design

#872 docs: added typography page
  website/docs/design/foundations/typography.md
Labels: documentation, design

#877 docs: update unpkg links with jsdelivr
  website/src/css/custom.css
Labels: documentation

#882 docs: added layout page
  website/docs/design/foundations/layout.md
Labels: documentation, design

#886 feat(tokens): update typography weights
  packages/design-tokens/styles/_typography.scss
Labels: enhancement

#887 docs: update typography styles & API
  website/docs/development/headless-styles/Typography.mdx
  website/src/css/custom.css
  website/src/pages/index.js
Labels: documentation

#888 docs: update SelectSizes preview
  website/src/components/Select/SelectSizes.preview.js
Labels: documentation

#890 fix(tokens): update themes.scss
  packages/design-tokens/styles/themes.scss
Labels: bug

#891 fix(tokens): remove prefers media tags
  .codesandbox/ci.json
  packages/design-tokens/styles/themes.scss
Labels: bug

#892 docs: use non-cached jsdelivr normalize url
  website/src/css/custom.css
Labels: bug, documentation

#909 fix: adjust icon package types to fix TS imports
  packages/icons/package.json
Labels: bug

#908 docs: add forms page
  website/docs/design/foundations/forms.md
Labels: documentation, design

#915 Feat/914 husky pre push
  .husky/pre-push
Labels: enhancement

#921 Chore/919 bump icons fs extra
  .pnp.cjs
  .yarn/cache/@types-fs-extra-npm-4.0.12-ef65781a9b-6a14044be3.zip
  .yarn/cache/@types-fs-extra-npm-9.0.13-12fb7badd7-add79e212a.zip
  .yarn/cache/fs-extra-npm-11.1.0-2cd157426f-5ca476103f.zip
  packages/icons/package.json
  yarn.lock
Labels: enhancement

#933 feat(headless-styles): add kind option to form label
  packages/headless-styles/sandbox/src/components/FormLabel.jsx
  packages/headless-styles/src/components/FormLabel/chakraFormLabel.ts
  packages/headless-styles/src/components/FormLabel/formLabelCSS.module.css
  packages/headless-styles/src/components/FormLabel/formLabelCSS.ts
  packages/headless-styles/src/components/FormLabel/formLabelJS.ts
  packages/headless-styles/src/components/FormLabel/generated/formLabelCSS.module.ts
  packages/headless-styles/src/components/FormLabel/shared.ts
  packages/headless-styles/src/components/FormLabel/types.ts
  packages/headless-styles/tests/formLabel/formLabelCSS.test.ts
  packages/headless-styles/tests/formLabel/formLabelJS.test.ts
Labels: enhancement

#934 docs(headless-styles): add new kind option for form label docs
  website/docs/development/headless-styles/FormControl.mdx
Labels: documentation
