Repository pluralsight/pando, pull requests merged in 2022-03, with the labels that each got.

#99 build: add global css configs to tokens package
  packages/design-tokens/fonts.css
  packages/design-tokens/normalize.css
  packages/design-tokens/package.json
  website/src/css/custom.css
Labels: enhancement

#102 chore: fix grammar errors
  website/docs/development/getting-started/installation.md
  website/docs/development/packages/tokens/colors.mdx
Labels: documentation

#119 revert(tokens): change files back to original value
  packages/design-tokens/package.json
Labels: bug

#122 fix: update website config to use design.pluralsight.com
  website/docusaurus.config.js
  website/static/CNAME
Labels: bug, documentation

#128 docs: add initial icons to packages section
  website/docs/development/getting-started/installation.md
  website/docs/development/getting-started/usage.md
  website/docs/development/packages/icons/_category_.yml
  website/docs/development/packages/icons/intro.md
Labels: documentation

#120 Add types field to tokens package.json
  packages/design-tokens/package.json
Labels: enhancement

#129 test: confirm icons publish in CI
  .github/workflows/publish_prereleases.yml
  packages/icons/README.md
Labels: bug

#133 docs: add framework icons to LiveExamplesTabs
  website/src/components/LiveExampleTabs/LiveExampleTabs.js
  website/src/components/LiveExampleTabs/LiveExampleTabs.module.css
Labels: documentation

#137 docs: add algolia search & update styles
  .pnp.cjs
  website/docusaurus.config.js
  website/package.json
  website/src/css/custom.css
  yarn.lock
Labels: documentation

#140 refactor(tokens): update fonts & normalize to use new font settings
  packages/design-tokens/fonts.css
  packages/design-tokens/normalize.css
Labels: enhancement
