Repository pluralsight/pando, pull requests merged in 2023-02, with the labels that each got.

#1049 refactor(headless-styles): update Tooltip to use disabled
  packages/headless-styles/src/components/Tooltip/generated/tooltipCSS.module.ts
  packages/headless-styles/src/components/Tooltip/shared.ts
  packages/headless-styles/src/components/Tooltip/tooltipCSS.module.css
  packages/headless-styles/src/components/shared/generated/tooltip.module.ts
  packages/headless-styles/src/components/shared/tooltip.module.css
  packages/headless-styles/tests/tooltip/tooltipCSS.test.ts
  packages/headless-styles/tests/tooltip/tooltipJS.test.ts
Labels: enhancement

#1050 feat(design-tokens): add scrollbar styles to _core.scss
  packages/design-tokens/styles/_core.scss
Labels: enhancement

#1053 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1055 feat(design-tokens): update class to use pando-<theme> selector
  packages/design-tokens/utils/platforms/web.cjs
Labels: enhancement

#1058 docs: update colors.mdx themes section
  website/docs/development/tokens/colors.mdx
Labels: documentation

#1059 Fix/1001 camelcase warnings
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/standard.js
  packages/headless-styles/sandbox/src/components/Tabs.jsx
  packages/headless-styles/src/components/Avatar/generated/avatarCSS.module.ts
  packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
  packages/headless-styles/src/components/Checkbox/checkboxJS.ts
  packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
  packages/headless-styles/src/components/ConfirmDialog/generated/confirmDialogCSS.module.ts
  packages/headless-styles/src/components/Input/chakraInput.ts
  packages/headless-styles/src/components/Input/generated/inputCSS.module.ts
  packages/headless-styles/src/components/Menu/generated/menuCSS.module.ts
  packages/headless-styles/src/components/Popover/generated/popoverCSS.module.ts
  packages/headless-styles/src/components/Radio/chakraRadio.ts
  packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
  packages/headless-styles/src/components/Radio/radioJS.ts
  packages/headless-styles/src/components/Select/chakraSelect.ts
  packages/headless-styles/src/components/Switch/chakraSwitch.ts
  packages/headless-styles/src/components/Switch/generated/switchCSS.module.ts
  packages/headless-styles/src/components/Tabs/generated/tabsCSS.module.ts
  packages/headless-styles/src/components/Tabs/tabsJS.ts
  packages/headless-styles/src/components/Tag/generated/tagCSS.module.ts
  packages/headless-styles/src/components/TextLink/generated/textLinkCSS.module.ts
  packages/headless-styles/src/components/Textarea/chakraTextarea.ts
  packages/headless-styles/src/components/shared/generated/input.module.ts
  packages/headless-styles/src/components/shared/generated/states.module.ts
  packages/headless-styles/src/components/shared/generated/tooltip.module.ts
  packages/headless-styles/src/utils/helpers.ts
Labels: bug

#1061 Revert "Fix/1001 camelcase warnings"
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/standard.js
  packages/headless-styles/sandbox/src/components/Tabs.jsx
  packages/headless-styles/src/components/Avatar/generated/avatarCSS.module.ts
  packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
  packages/headless-styles/src/components/Checkbox/checkboxJS.ts
  packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
  packages/headless-styles/src/components/ConfirmDialog/generated/confirmDialogCSS.module.ts
  packages/headless-styles/src/components/Input/chakraInput.ts
  packages/headless-styles/src/components/Input/generated/inputCSS.module.ts
  packages/headless-styles/src/components/Menu/generated/menuCSS.module.ts
  packages/headless-styles/src/components/Popover/generated/popoverCSS.module.ts
  packages/headless-styles/src/components/Radio/chakraRadio.ts
  packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
  packages/headless-styles/src/components/Radio/radioJS.ts
  packages/headless-styles/src/components/Select/chakraSelect.ts
  packages/headless-styles/src/components/Switch/chakraSwitch.ts
  packages/headless-styles/src/components/Switch/generated/switchCSS.module.ts
  packages/headless-styles/src/components/Tabs/generated/tabsCSS.module.ts
  packages/headless-styles/src/components/Tabs/tabsJS.ts
  packages/headless-styles/src/components/Tag/generated/tagCSS.module.ts
  packages/headless-styles/src/components/TextLink/generated/textLinkCSS.module.ts
  packages/headless-styles/src/components/Textarea/chakraTextarea.ts
  packages/headless-styles/src/components/shared/generated/input.module.ts
  packages/headless-styles/src/components/shared/generated/states.module.ts
  packages/headless-styles/src/components/shared/generated/tooltip.module.ts
  packages/headless-styles/src/utils/helpers.ts
Labels: bug

#1062 refactor(headless-styles): kill unused Chakra examples
  packages/headless-styles/src/chakra.ts
  packages/headless-styles/src/components/Admonition/chakraAlert.ts
  packages/headless-styles/src/components/Avatar/chakraAvatar.ts
  packages/headless-styles/src/components/Badge/chakraBadge.ts
  packages/headless-styles/src/components/Button/chakraButton.ts
  packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
  packages/headless-styles/src/components/FormControl/chakraFormControl.ts
  packages/headless-styles/src/components/FormLabel/chakraFormLabel.ts
  packages/headless-styles/src/components/Input/chakraInput.ts
  packages/headless-styles/src/components/Modal/chakraModal.ts
  packages/headless-styles/src/components/Popover/chakraPopover.ts
  packages/headless-styles/src/components/Progress/chakraProgress.ts
  packages/headless-styles/src/components/Radio/chakraRadio.ts
  packages/headless-styles/src/components/Select/chakraSelect.ts
  packages/headless-styles/src/components/Switch/chakraSwitch.ts
  packages/headless-styles/src/components/Table/chakraTable.ts
  packages/headless-styles/src/components/Tabs/chakraTab.ts
  packages/headless-styles/src/components/Tag/chakraTag.ts
  packages/headless-styles/src/components/TextLink/chakraTextLink.ts
  packages/headless-styles/src/components/Textarea/chakraTextarea.ts
  packages/headless-styles/src/components/Tooltip/chakraTooltip.ts
Labels: enhancement

#1063 Feat/promote use theme
  packages/react-utils/index.experimental.js
  packages/react-utils/index.stable.js
Labels: enhancement

#1066 docs: add useTheme api page
  website/docs/development/react-utils/useTheme.mdx
Labels: documentation

#1088 Fix/1071 js radio focus
  packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
  packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
  packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
  packages/headless-styles/src/components/Radio/radioCSS.module.css
  packages/headless-styles/src/components/shared/defaultOptions.ts
  packages/headless-styles/tests/checkbox/checkboxCSS.test.ts
  packages/headless-styles/tests/radio/radioCSS.test.ts
  packages/headless-styles/tests/switch/switchCSS.test.ts
Labels: bug

#1091 refactor(website): add fwv prop back in since it meets our browser re…
  packages/headless-styles/src/components/Admonition/admonitionCSS.module.css
  packages/headless-styles/src/components/Admonition/generated/admonitionCSS.module.ts
  packages/headless-styles/src/components/Tooltip/generated/tooltipCSS.module.ts
  packages/headless-styles/src/components/Tooltip/tooltipCSS.module.css
  website/src/css/custom.css
Labels: bug

#1095 build(react-utils): update babel config to use runtime helper
  .pnp.cjs
  .yarn/cache/@types-babel__plugin-transform-runtime-npm-7.9.2-686ddccae8-0eb18bf14b.zip
  .yarn/sdks/prettier/package.json
  packages/react-utils/package.json
  packages/react-utils/rollup.config.mjs
  yarn.lock
Labels: bug

#1094 docs: add clarity tracking script
  website/docusaurus.config.js
  website/static/clarity.js
Labels: documentation

#1100 docs: update versioned setup links for beta
  .pnp.cjs
  .yarn/cache/@pluralsight-react-utils-npm-0.3.1-rc-0656fe-c400c3d9a8-159152a480.zip
  .yarn/cache/@pluralsight-react-utils-npm-0.3.1-rc-5d4a4f-1ab0bc3cf7-c6a1973212.zip
  website/package.json
  website/versioned_docs/version-0.3.1-beta/development/getting-started/installation.md
  website/versioned_docs/version-0.3.1-beta/development/getting-started/migration.md
  yarn.lock
Labels: bug, documentation

#1101 build: update versions.mjs for rc release
  versions.mjs
Labels: github_actions

#1106 docs: add display api information
  website/docs/development/headless-styles/Typography.mdx
  website/versioned_docs/version-0.4.0-rc/development/headless-styles/Typography.mdx
Labels: documentation

#1107 docs: fix typo in typography
  website/docs/development/headless-styles/Typography.mdx
Labels: documentation

#1108 docs(headless-styles): add hidden label example
  website/docs/development/headless-styles/FormControl.mdx
  website/src/theme/ReactLiveScope/index.js
Labels: documentation

#1111 fix(design-tokens): add missing fvs props in _typography.scss
  packages/design-tokens/styles/_typography.scss
Labels: bug

#1113 build: update versions to 0.4.1
  versions.mjs
Labels: github_actions
