Repository pluralsight/pando, pull requests merged in 2023-05, with the labels that each got.

#1250 docs: correct typo in accessibility heading
  website/docs/reference/components/pagination.mdx
Labels: documentation

#1256 fix: add package filtering in publish.js based on Node env
  scripts/release/publish.js
Labels: bug

#1263 docs(ref): update admonition.mdx
  .pnp.cjs
  .yarn/cache/@pluralsight-react-npm-0.4.1-next-fa8dbf-5d5ae9ef7c-992a0aef28.zip
  website/docs/reference/components/admonition.mdx
  website/package.json
  website/src/components/DocsLinkBar/DocsLinkBar.js
  website/src/css/custom.css
  website/src/theme/ReactLiveScope/index.js
  yarn.lock
Labels: enhancement

#1269 docs: update Avatar page
  .pnp.cjs
  .yarn/cache/@pluralsight-react-npm-0.4.1-next-89c601-b8b37971ca-98d888e332.zip
  .yarn/cache/@pluralsight-react-npm-0.4.1-next-fa8dbf-5d5ae9ef7c-992a0aef28.zip
  packages/react/src/components/Avatar.tsx
  packages/sandbox/package.json
  website/docs/reference/components/admonition.mdx
  website/docs/reference/components/avatar.mdx
  website/src/css/custom.css
  website/src/theme/ReactLiveScope/index.js
  yarn.lock
Labels: enhancement

#1278 feat(headless-styles): convert admonition to scss
  packages/headless-styles/sandbox_old/plugins/css-to-ts/convert-rules/composes.js
  packages/headless-styles/sandbox_old/plugins/css-to-ts/utils/addProperty.js
  packages/headless-styles/sandbox_old/plugins/css-to-ts/utils/deepMerge.js
  packages/headless-styles/src/components/Admonition/admonitionCSS.module.css
  packages/headless-styles/src/components/Admonition/admonitionCSS.scss
  packages/headless-styles/src/components/Admonition/admonitionCSS.ts
  packages/headless-styles/src/components/Admonition/admonitionJS.ts
  packages/headless-styles/src/components/Admonition/generated/admonitionCSS.ts
  packages/headless-styles/src/components/Admonition/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/admonition/admonitionCSS.test.ts
  packages/headless-styles/tests/admonition/admonitionJS.test.ts
Labels: enhancement

#1282 Feat/1242 alert scss
  packages/headless-styles/sandbox_old/src/App.jsx
  packages/headless-styles/sandbox_old/src/components/PromptDialog.jsx
  packages/headless-styles/src/components/Alert/alertCSS.module.css
  packages/headless-styles/src/components/Alert/alertCSS.scss
  packages/headless-styles/src/components/Alert/alertCSS.ts
  packages/headless-styles/src/components/Alert/alertJS.ts
  packages/headless-styles/src/components/Alert/generated/alertCSS.module.ts
  packages/headless-styles/src/components/Alert/generated/alertCSS.ts
  packages/headless-styles/src/components/shared/dialog.scss
  packages/headless-styles/src/components/shared/generated/keyframes.ts
  packages/headless-styles/src/components/shared/keyframes.scss
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/alert/alertCSS.test.ts
  packages/headless-styles/tests/alert/alertJS.test.ts
Labels: enhancement

#1290 feat(headless-styles): convert avatar to scss
  packages/headless-styles/src/components/Avatar/avatarCSS.scss
  packages/headless-styles/src/components/Avatar/avatarCSS.ts
  packages/headless-styles/src/components/Avatar/avatarJS.ts
  packages/headless-styles/src/components/Avatar/generated/avatarCSS.ts
  packages/headless-styles/src/components/Avatar/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/avatar/avatarCSS.test.ts
  packages/headless-styles/tests/avatar/avatarLabel.test.ts
Labels: enhancement

#1291 feat(headless-styles): convert badge to scss
  packages/headless-styles/src/components/Badge/badgeCSS.scss
  packages/headless-styles/src/components/Badge/badgeCSS.ts
  packages/headless-styles/src/components/Badge/badgeJS.ts
  packages/headless-styles/src/components/Badge/generated/badgeCSS.ts
  packages/headless-styles/src/components/Badge/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/badge/badgeCSS.test.ts
  packages/headless-styles/tests/badge/badgeJS.test.ts
Labels: enhancement

#1297 Feat/1242 field messages scss
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.module.css
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.scss
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.ts
  packages/headless-styles/src/components/ErrorMessage/errorMessageJS.ts
  packages/headless-styles/src/components/ErrorMessage/generated/errorMessageCSS.ts
  packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.module.css
  packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.scss
  packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.ts
  packages/headless-styles/src/components/FieldMessage/fieldMessageJS.ts
  packages/headless-styles/src/components/FieldMessage/generated/fieldMessageCSS.ts
  packages/headless-styles/src/components/shared/_fieldMessage.scss
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/errorMessage/errorMessageCSS.test.ts
  packages/headless-styles/tests/fieldMessage/fieldMessageCSS.test.ts
Labels: enhancement

#1298 feat(headless-styles): convert form control to scss
  packages/headless-styles/src/components/FormControl/formControlCSS.module.css
  packages/headless-styles/src/components/FormControl/formControlCSS.scss
  packages/headless-styles/src/components/FormControl/formControlCSS.ts
  packages/headless-styles/src/components/FormControl/formControlJS.ts
  packages/headless-styles/src/components/FormControl/generated/formControlCSS.ts
  packages/headless-styles/src/components/FormControl/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/formControl/formControlCSS.test.ts
Labels: enhancement

#1296 feat(headless-styles): convert circular progress to scss
  packages/headless-styles/src/components/Button/generated/buttonCSS.ts
  packages/headless-styles/src/components/CircularProgress/circularProgressCSS.scss
  packages/headless-styles/src/components/CircularProgress/circularProgressCSS.ts
  packages/headless-styles/src/components/CircularProgress/circularProgressJS.ts
  packages/headless-styles/src/components/CircularProgress/generated/circularProgressCSS.ts
  packages/headless-styles/src/components/CircularProgress/shared.ts
  packages/headless-styles/src/components/Progress/progressCSS.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/circular-progress/circularProgressCSS.test.ts
  packages/headless-styles/tests/circular-progress/circularProgressJS.test.ts
  packages/headless-styles/tests/progress/progressCSS.test.ts
Labels: enhancement

#1299 feat(headless-styles): convert form label to scss
  packages/headless-styles/src/components/FormLabel/formLabelCSS.scss
  packages/headless-styles/src/components/FormLabel/formLabelCSS.ts
  packages/headless-styles/src/components/FormLabel/formLabelJS.ts
  packages/headless-styles/src/components/FormLabel/generated/formLabelCSS.ts
  packages/headless-styles/src/components/FormLabel/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/formLabel/formLabelCSS.test.ts
Labels: enhancement

#1300 feat(headless-styles): convert grid to scss
  packages/headless-styles/src/components/Grid/generated/gridCSS.ts
  packages/headless-styles/src/components/Grid/gridCSS.scss
  packages/headless-styles/src/components/Grid/gridCSS.ts
  packages/headless-styles/src/components/Grid/gridJS.ts
  packages/headless-styles/tests/grid/gridCSS.test.ts
Labels: enhancement

#1301 feat(headless-styles): convert icon to scss
  packages/headless-styles/src/components/Icon/generated/iconCSS.ts
  packages/headless-styles/src/components/Icon/iconCSS.module.css
  packages/headless-styles/src/components/Icon/iconCSS.scss
  packages/headless-styles/src/components/Icon/iconCSS.ts
  packages/headless-styles/src/components/Icon/iconJS.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/icon/iconCSS.test.ts
Labels: enhancement

#1314 fix(hs): add has selector to skeletonCSS.module.css
  packages/headless-styles/src/components/Skeleton/skeletonCSS.module.css
Labels: bug

#1307 Feat/1242 input scss
  packages/headless-styles/src/components/Input/generated/inputCSS.module.ts
  packages/headless-styles/src/components/Input/generated/inputCSS.ts
  packages/headless-styles/src/components/Input/inputCSS.module.css
  packages/headless-styles/src/components/Input/inputCSS.scss
  packages/headless-styles/src/components/Input/inputCSS.ts
  packages/headless-styles/src/components/Input/inputJS.ts
  packages/headless-styles/src/components/Input/shared.ts
  packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
  packages/headless-styles/src/components/Select/generated/selectCSS.ts
  packages/headless-styles/src/components/Select/selectCSS.module.css
  packages/headless-styles/src/components/Select/selectCSS.scss
  packages/headless-styles/src/components/Select/selectCSS.ts
  packages/headless-styles/src/components/Select/selectJS.ts
  packages/headless-styles/src/components/Select/shared.ts
  packages/headless-styles/src/components/shared/_input.scss
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/input/inputCSS.test.ts
  packages/headless-styles/tests/input/inputJS.test.ts
  packages/headless-styles/tests/select/selectCSS.test.ts
Labels: enhancement

#1316 Feat/1242 pagination scss
  packages/headless-styles/sandbox_old/src/components/Pagination.jsx
  packages/headless-styles/src/components/Pagination/generated/paginationCSS.ts
  packages/headless-styles/src/components/Pagination/paginationCSS.module.css
  packages/headless-styles/src/components/Pagination/paginationCSS.scss
  packages/headless-styles/src/components/Pagination/paginationCSS.ts
  packages/headless-styles/src/components/Pagination/paginationJS.ts
  packages/headless-styles/src/components/Pagination/shared.ts
  packages/headless-styles/src/components/Select/selectJS.ts
  packages/headless-styles/tests/pagination/paginationCSS.test.ts
Labels: enhancement

#1345 ci: don't trigger doc comment on merge_group
  .github/workflows/contributing.yml
Labels: github_actions

#1362 ci: add action to run yarn install and commit results on dependabot PRs
  .github/workflows/dependabot_dep_install.yml
Labels: github_actions

#1363 feat(hs): update TextLink to extend DefaultOptions
  packages/headless-styles/src/components/TextLink/shared.ts
  packages/headless-styles/src/components/TextLink/textLinkCSS.ts
  packages/headless-styles/src/components/TextLink/types.ts
  packages/headless-styles/tests/textLink/textLinkCSS.test.ts
Labels: enhancement

#1366 ci: update dependabot install action to run on pull_request_target
  .github/workflows/dependabot_dep_install.yml
Labels: github_actions

#1364 feat(headless-styles): convert skeleton to scss
  packages/headless-styles/src/components/Skeleton/generated/skeletonCSS.ts
  packages/headless-styles/src/components/Skeleton/shared.ts
  packages/headless-styles/src/components/Skeleton/skeletonCSS.scss
  packages/headless-styles/src/components/Skeleton/skeletonCSS.ts
  packages/headless-styles/src/components/Skeleton/skeletonJS.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/skeleton/skeletonCSS.test.ts
Labels: enhancement

#1368 feat(headless-styles): convert switch to scss
  packages/headless-styles/src/components/Switch/generated/switchCSS.module.ts
  packages/headless-styles/src/components/Switch/generated/switchCSS.ts
  packages/headless-styles/src/components/Switch/shared.ts
  packages/headless-styles/src/components/Switch/switchCSS.module.css
  packages/headless-styles/src/components/Switch/switchCSS.scss
  packages/headless-styles/src/components/Switch/switchCSS.ts
  packages/headless-styles/src/components/Switch/switchJS.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/switch/switchCSS.test.ts
  packages/headless-styles/tests/switch/switchJS.test.ts
Labels: enhancement

#1375 feat(headless-styles): convert tag to scss
  packages/headless-styles/src/components/Tag/generated/tagCSS.ts
  packages/headless-styles/src/components/Tag/shared.ts
  packages/headless-styles/src/components/Tag/tagCSS.scss
  packages/headless-styles/src/components/Tag/tagCSS.ts
  packages/headless-styles/src/components/Tag/tagJS.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/tag/tagCSS.test.ts
Labels: enhancement

#1376 feat(headless-styles): convert textarea to scss
  packages/headless-styles/src/components/Textarea/generated/textareaCSS.module.ts
  packages/headless-styles/src/components/Textarea/generated/textareaCSS.ts
  packages/headless-styles/src/components/Textarea/shared.ts
  packages/headless-styles/src/components/Textarea/textareaCSS.module.css
  packages/headless-styles/src/components/Textarea/textareaCSS.scss
  packages/headless-styles/src/components/Textarea/textareaCSS.ts
  packages/headless-styles/src/components/Textarea/textareaJS.ts
  packages/headless-styles/src/styles.ts
  packages/headless-styles/tests/textarea/textareaCSS.test.ts
  packages/headless-styles/tests/textarea/textareaJS.test.ts
Labels: enhancement

#1384 fix(hs): update Icon types to be conditional based on ariaHidden result
  packages/headless-styles/src/components/Badge/shared.ts
  packages/headless-styles/src/components/Icon/iconCSS.ts
  packages/headless-styles/src/components/Icon/shared.ts
  packages/headless-styles/src/components/Icon/types.ts
  packages/headless-styles/src/components/IconButton/shared.ts
  packages/headless-styles/src/components/Input/shared.ts
  packages/headless-styles/src/components/Select/shared.ts
  packages/headless-styles/tests/badge/badgeCSS.test.ts
  packages/headless-styles/tests/badge/badgeJS.test.ts
  packages/headless-styles/tests/icon/iconCSS.test.ts
  packages/headless-styles/tests/icon/iconJS.test.ts
  packages/headless-styles/tests/iconButton/iconButtonCSS.test.ts
Labels: bug

#1393 feat(hs): update Grid API to be more flexbile
  .pnp.cjs
  packages/headless-styles/package.json
  packages/headless-styles/sandbox_old/src/components/Grid.jsx
  packages/headless-styles/src/components/Grid/shared.ts
  packages/headless-styles/src/components/Grid/types.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/tests/grid/gridCSS.test.ts
  packages/headless-styles/tests/grid/gridJS.test.ts
  yarn.lock
Labels: enhancement

#1397 fix(hs): add CSSProperties type to grid helpers
  packages/headless-styles/src/components/Grid/shared.ts
Labels: bug

#1421 Refactor/error message 1419
  packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.ts
  packages/headless-styles/src/components/ErrorMessage/shared.ts
  packages/headless-styles/src/components/ErrorMessage/types.ts
  packages/headless-styles/tests/errorMessage/errorMessageCSS.test.ts
Labels: enhancement

#1424 fix(react): forwards area and areas props for grid components
  packages/react/src/components/Grid.tsx
Labels: bug

#1430 feat(hs): update FormLabel to compliment components
  packages/headless-styles/src/components/FormLabel/formLabelCSS.ts
  packages/headless-styles/src/components/FormLabel/shared.ts
  packages/headless-styles/src/components/FormLabel/types.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/tests/formLabel/formLabelCSS.test.ts
Labels: enhancement
