Repository pluralsight/pando, pull requests merged in 2023-03, with the labels that each got.

#1129 feat(icons): add Figma icon
  packages/icons/src/brands/figma.svg
  packages/icons/src/string/generated/iconStrings.ts
Labels: enhancement

#1143 feat(icons): add YT and Discord icons to brand section
  packages/icons/src/brands/discord.svg
  packages/icons/src/brands/you-tube.svg
Labels: enhancement

#1149 fix(headles-styles): allow tooltip content to expand up to 300px
  packages/headless-styles/src/components/Tooltip/generated/tooltipCSS.module.ts
  packages/headless-styles/src/components/Tooltip/tooltipCSS.module.css
Labels: bug

#1152 fix(headless-styles): swap quotes in checkbox/radio JS APIs to match …
  packages/headless-styles/src/components/Checkbox/checkboxJS.ts
  packages/headless-styles/src/components/Radio/radioJS.ts
Labels: bug

#1162 Refactor/1131 feature confirmdialog and modal should share return props
  packages/headless-styles/src/components/ConfirmDialog/shared.ts
  packages/headless-styles/src/components/Modal/shared.ts
  packages/headless-styles/src/components/Popover/shared.ts
  packages/headless-styles/src/components/shared/helpers/dialog.ts
  packages/headless-styles/src/utils/a11yHelpers.ts
  packages/headless-styles/tests/confirmDialog/confirmDialogCSS.test.ts
  packages/headless-styles/tests/modal/modalCSS.test.ts
Labels: enhancement

#1177 fix(hs): kill added border to icon button styles
  packages/headless-styles/src/components/IconButton/generated/iconButtonCSS.module.ts
  packages/headless-styles/src/components/IconButton/iconButtonCSS.module.css
Labels: bug

#1178 1176 docs update buttoniconbutton examples
  .pnp.cjs
  .yarn/cache/@pluralsight-headless-styles-npm-0.4.1-next-d533e5-d53f4454cf-4b2bb246ea.zip
  .yarn/cache/@pluralsight-headless-styles-npm-0.4.1-next-eec231-725d14a874-d741b14731.zip
  website/docs/reference/components/icon-button.mdx
  yarn.lock
Labels: enhancement

#1190 docs: update Pando branding in versioning.md
  website/docs/learn/about-pando/versioning.md
Labels: documentation
