Repository pluralsight/pando, pull requests merged in 2023-01, with the labels that each got.

#943 Revert "build(headless-styles): make headless-styles tree-shakeable"
  packages/headless-styles/npm/browser.js
  packages/headless-styles/npm/index.js
  packages/headless-styles/package.json
  packages/headless-styles/rollup.config.mjs
Labels: bug

#942 feat(headless-styles): update border color for inputs
  packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
  packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
  packages/headless-styles/src/components/Input/generated/InputCSS.module.ts
  packages/headless-styles/src/components/Input/inputCSS.module.css
  packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
  packages/headless-styles/src/components/Radio/radioCSS.module.css
  packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
  packages/headless-styles/src/components/Select/selectCSS.module.css
  packages/headless-styles/src/components/Textarea/generated/textareaCSS.module.ts
  packages/headless-styles/src/components/Textarea/textareaCSS.module.css
Labels: enhancement

#946 ci: update ci.json
  .codesandbox/ci.json
Labels: enhancement

#947 feat(headless-styles): update list styles so they are opt-in using cl…
  packages/design-tokens/styles/_lists.scss
Labels: enhancement

#945 Treeshake headless styles
  packages/headless-styles/npm/browser.js
  packages/headless-styles/npm/index.js
  packages/headless-styles/package.json
  packages/headless-styles/rollup.config.mjs
Labels: enhancement

#948 Docs/944 opt in list styles
  website/src/css/custom.css
Labels: documentation

#952 Removed optional flag from component anatomy list
  website/versioned_docs/version-0.3.1-beta/design/components/form-control.md
Labels: documentation, design

#964 chore: update README banner
  README.md
Labels: documentation

#973 fix(headless-styles): move menu positioning from tooltip to menu
  packages/headless-styles/src/components/Menu/generated/menuCSS.module.ts
  packages/headless-styles/src/components/Menu/generated/menuPositioning.module.ts
  packages/headless-styles/src/components/Menu/menuCSS.module.css
  packages/headless-styles/src/components/Menu/menuCSS.ts
  packages/headless-styles/src/components/Menu/menuJS.ts
  packages/headless-styles/src/components/Menu/menuPositioning.module.css
  packages/headless-styles/src/components/Menu/shared.ts
Labels: bug

#985 chore: update workspace packageManager to match current version used
  packages/design-tokens/package.json
  packages/headless-styles/package.json
  packages/icons/package.json
  packages/react-utils/package.json
  packages/shared/package.json
  website/package.json
Labels: bug

#988 fix: adjust jest test match string to pick up missing tests
  jest.config.js
Labels: bug

#1002 docs: add missing Props iconOptions property
  website/docs/development/headless-styles/Checkbox.mdx
Labels: documentation

#958 Feat/879 Create useTheme Hook
  packages/react-utils/src/hooks/useTheme.ts
  packages/react-utils/src/index.ts
  packages/react-utils/tests/hooks/useTheme.test.tsx
Labels: enhancement

#1012 docs: fix Basic Table initial preview
  website/src/components/Table/BasicTable.preview.js
Labels: bug, documentation

#1016 Fix/1006 bug tabs apis are spelled incorrectly
  packages/headless-styles/index.experimental.js
  packages/headless-styles/index.stable.js
  packages/headless-styles/sandbox/src/components/Tabs.jsx
  packages/headless-styles/src/chakra.ts
  packages/headless-styles/src/components/Tab/types.ts
  packages/headless-styles/src/components/Tabs/chakraTab.ts
  packages/headless-styles/src/components/Tabs/generated/tabsCSS.module.ts
  packages/headless-styles/src/components/Tabs/shared.ts
  packages/headless-styles/src/components/Tabs/tabsCSS.module.css
  packages/headless-styles/src/components/Tabs/tabsCSS.ts
  packages/headless-styles/src/components/Tabs/tabsJS.ts
  packages/headless-styles/src/components/Tabs/types.ts
  packages/headless-styles/src/generatedStyles.ts
  packages/headless-styles/src/index.ts
  packages/headless-styles/src/types.ts
  packages/headless-styles/tests/tab/tabCSS.test.ts
  packages/headless-styles/tests/tab/tabJS.test.ts
Labels: bug

#1021 docs(website): update README.md
  website/README.md
Labels: documentation

#1023 feat(headless-styles): promote select option APIs to next
  packages/headless-styles/index.experimental.js
  packages/headless-styles/index.stable.js
Labels: enhancement

#1024 Fix/1004 js progress width
  packages/headless-styles/sandbox/src/components/Progress.jsx
  packages/headless-styles/src/components/Progress/generated/progressCSS.module.ts
  packages/headless-styles/src/components/Progress/progressCSS.module.css
  packages/headless-styles/src/components/Progress/progressCSS.ts
  packages/headless-styles/tests/progress/progressCSS.test.ts
  packages/headless-styles/tests/progress/progressJS.test.ts
Labels: bug

#1039 Fix/1038 parentless pseudo class in js
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/standard.js
  packages/headless-styles/src/components/ConfirmDialog/confirmDialogJS.ts
  packages/headless-styles/src/components/ConfirmDialog/generated/confirmDialogCSS.module.ts
  packages/headless-styles/src/components/Input/generated/inputCSS.module.ts
  packages/headless-styles/src/components/Input/inputCSS.module.css
  packages/headless-styles/src/components/Input/inputJS.ts
  packages/headless-styles/src/components/Modal/chakraModal.ts
  packages/headless-styles/src/components/Modal/modalJS.ts
Labels: bug

#1042 Fix/1032 add shared btn styles
  .pnp.cjs
  packages/headless-styles/sandbox/package.json
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-inputs/convert-inputs.js
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-inputs/write-file.js
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/composes.js
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/convertToJS.js
  packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/tokenMap.js
  packages/headless-styles/sandbox/plugins/transformCSStoTS.js
  packages/headless-styles/sandbox/src/App.jsx
  packages/headless-styles/sandbox/src/components/Button.jsx
  packages/headless-styles/sandbox/vite.config.js
  packages/headless-styles/src/components/Button/buttonCSS.module.css
  packages/headless-styles/src/components/Button/buttonCSS.ts
  packages/headless-styles/src/components/Button/buttonJS.ts
  packages/headless-styles/src/components/Button/generated/buttonCSS.module.ts
  packages/headless-styles/src/components/IconButton/generated/iconButtonCSS.module.ts
  packages/headless-styles/src/components/IconButton/iconButtonCSS.module.css
  packages/headless-styles/src/components/shared/button.module.css
  packages/headless-styles/src/components/shared/generated/button.module.ts
  yarn.lock
Labels: bug, enhancement

#1043 Fix/1003 confirm button spacing
  packages/headless-styles/sandbox/src/components/ConfirmDialog.jsx
  packages/headless-styles/src/components/ConfirmDialog/confirmDialogCSS.module.css
  packages/headless-styles/src/components/ConfirmDialog/confirmDialogJS.ts
  packages/headless-styles/src/components/ConfirmDialog/generated/confirmDialogCSS.module.ts
Labels: bug
